// Original file: src\cc\arduino\cli\commands\v1\lib.proto

export enum LibraryLocation {
  LIBRARY_LOCATION_IDE_BUILTIN = 0,
  LIBRARY_LOCATION_USER = 1,
  LIBRARY_LOCATION_PLATFORM_BUILTIN = 2,
  LIBRARY_LOCATION_REFERENCED_PLATFORM_BUILTIN = 3,
  LIBRARY_LOCATION_UNMANAGED = 4,
}
